#!/bin/bash

source spinner

spinner &
spinner_pid=$!

rpmDir="repo/x86_64/RPMS.hasher"
srpmDir="repo/SRPMS.hasher"

for (( i=0 ; i<$(( $(nproc) / 2 )) ; i++ )); do
    mv "$HOME/hasher$i/$rpmDir/*" "$HOME/hasher/$rpmDir/"
    mv "$HOME/hasher$i/$srpmDir/*" "$HOME/hasher/$srpmDir/"
done

for (( i=0; i<$(( $(nproc) / 2 )) ; i++ )); do
    cp -al "$HOME/hasher/$rpmDir/*" "$HOME/hasher$i/$rpmDir/"
    cp -al "$HOME/hasher/$srpmDir/*" "$HOME/hasher$i/$srpmDir/"
done

kill "$spinner_pid" >/dev/null 2>&1
echo
